#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'finished' $1
  rm -rf $3
  mkdir $3
  mv LOGS/* $3
  echo;	echo '***';	echo '***';	echo '***';	echo '***';	echo
}


date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_part1_header part1.mod LOGS_part1
do_one inlist_part2_header part2.mod LOGS_part2
do_one inlist_part3_header part3.mod LOGS_part3

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists'

